//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class AccelarateType : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        byte fAccelerate;
        public byte Accelerate
        {
            get { return fAccelerate; }
            set { SetPropertyValue<byte>(nameof(Accelerate), ref fAccelerate, value); }
        }
        char fCode;
        public char Code
        {
            get { return fCode; }
            set { SetPropertyValue<char>(nameof(Code), ref fCode, value); }
        }
        [Association(@"BusinessSettingsReferencesAccelarateType")]
        public XPCollection<BusinessSettings> BusinessSettingsCollection { get { return GetCollection<BusinessSettings>(nameof(BusinessSettingsCollection)); } }
        [Association(@"ProductReferencesAccelarateType")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
    }

}
