//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class BusinessSettings : XPObject
    {
        Customer fDeafultBusinessPartner;
        [Association(@"BusinessSettingsReferencesCustomer")]
        public Customer DeafultBusinessPartner
        {
            get { return fDeafultBusinessPartner; }
            set { SetPropertyValue<Customer>(nameof(DeafultBusinessPartner), ref fDeafultBusinessPartner, value); }
        }
        AccelarateType fDefaultAccelerate;
        [Association(@"BusinessSettingsReferencesAccelarateType")]
        public AccelarateType DefaultAccelerate
        {
            get { return fDefaultAccelerate; }
            set { SetPropertyValue<AccelarateType>(nameof(DefaultAccelerate), ref fDefaultAccelerate, value); }
        }
    }

}
