//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class CommonTrHeader : XPObject
    {
        string fIdentity;
        public string Identity
        {
            get { return fIdentity; }
            set { SetPropertyValue<string>(nameof(Identity), ref fIdentity, value); }
        }
        CommonTrType fCommonType;
        public CommonTrType CommonType
        {
            get { return fCommonType; }
            set { SetPropertyValue<CommonTrType>(nameof(CommonType), ref fCommonType, value); }
        }
        string fReference;
        public string Reference
        {
            get { return fReference; }
            set { SetPropertyValue<string>(nameof(Reference), ref fReference, value); }
        }
        Customer fCustomer;
        [Association(@"CommonTrHeaderReferencesCustomer")]
        public Customer Customer
        {
            get { return fCustomer; }
            set { SetPropertyValue<Customer>(nameof(Customer), ref fCustomer, value); }
        }
        int fPriority;
        [Indexed(Name = @"iPriority_CommonTrHeader")]
        public int Priority
        {
            get { return fPriority; }
            set { SetPropertyValue<int>(nameof(Priority), ref fPriority, value); }
        }
        DateTime fRecordingDate;
        public DateTime RecordingDate
        {
            get { return fRecordingDate; }
            set { SetPropertyValue<DateTime>(nameof(RecordingDate), ref fRecordingDate, value); }
        }
        int fStatus;
        public int Status
        {
            get { return fStatus; }
            set { SetPropertyValue<int>(nameof(Status), ref fStatus, value); }
        }
        [Association(@"IocpReferencesCommonTrHeader")]
        public XPCollection<Iocp> Iocps { get { return GetCollection<Iocp>(nameof(Iocps)); } }
        [Association(@"CommonTrDetailReferencesCommonTrHeader"), Aggregated]
        public XPCollection<CommonTrDetail> CommonTrDetails { get { return GetCollection<CommonTrDetail>(nameof(CommonTrDetails)); } }
    }

}
