//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class CommonTrType : XPObject
    {
        string fType;
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>(nameof(Type), ref fType, value); }
        }
        string fPrefix;
        public string Prefix
        {
            get { return fPrefix; }
            set { SetPropertyValue<string>(nameof(Prefix), ref fPrefix, value); }
        }
        bool fDateDepended;
        public bool DateDepended
        {
            get { return fDateDepended; }
            set { SetPropertyValue<bool>(nameof(DateDepended), ref fDateDepended, value); }
        }
        Customer fDefaultPartner;
        [Association(@"CommonTrTypeReferencesCustomer")]
        public Customer DefaultPartner
        {
            get { return fDefaultPartner; }
            set { SetPropertyValue<Customer>(nameof(DefaultPartner), ref fDefaultPartner, value); }
        }
        string fName;
        [ColumnDbDefaultValue("(N'')")]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        bool fCreatable;
        public bool Creatable
        {
            get { return fCreatable; }
            set { SetPropertyValue<bool>(nameof(Creatable), ref fCreatable, value); }
        }
        [Association(@"SorszamReferencesCommonTrType")]
        public XPCollection<Sorszam> Sorszams { get { return GetCollection<Sorszam>(nameof(Sorszams)); } }
    }

}
