//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class CommonTrDetail : XPObject
    {
        CommonTrHeader fCommonTrHeader;
        [Association(@"CommonTrDetailReferencesCommonTrHeader")]
        public CommonTrHeader CommonTrHeader
        {
            get { return fCommonTrHeader; }
            set { SetPropertyValue<CommonTrHeader>(nameof(CommonTrHeader), ref fCommonTrHeader, value); }
        }
        int fItemNum;
        public int ItemNum
        {
            get { return fItemNum; }
            set { SetPropertyValue<int>(nameof(ItemNum), ref fItemNum, value); }
        }
        Product fProduct;
        [Association(@"CommonTrDetailReferencesProduct")]
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        double fPerformedQty;
        public double PerformedQty
        {
            get { return fPerformedQty; }
            set { SetPropertyValue<double>(nameof(PerformedQty), ref fPerformedQty, value); }
        }
        double fQuantity;
        public double Quantity
        {
            get { return fQuantity; }
            set { SetPropertyValue<double>(nameof(Quantity), ref fQuantity, value); }
        }
        uint fCalcLcNumber;
        public uint CalcLcNumber
        {
            get { return fCalcLcNumber; }
            set { SetPropertyValue<uint>(nameof(CalcLcNumber), ref fCalcLcNumber, value); }
        }
        [Association(@"IocpReferencesCommonTrDetail")]
        public XPCollection<Iocp> Iocps { get { return GetCollection<Iocp>(nameof(Iocps)); } }
        [Association(@"StockHistoryReferencesCommonTrDetail")]
        public XPCollection<StockHistory> StockHistories { get { return GetCollection<StockHistory>(nameof(StockHistories)); } }
    }

}
