//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class Customer : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        int fSegment;
        [Indexed(Name = @"iSegment_Customer")]
        public int Segment
        {
            get { return fSegment; }
            set { SetPropertyValue<int>(nameof(Segment), ref fSegment, value); }
        }
        int fPriority;
        [Indexed(Name = @"iPriority_Customer")]
        public int Priority
        {
            get { return fPriority; }
            set { SetPropertyValue<int>(nameof(Priority), ref fPriority, value); }
        }
        string fCountry;
        public string Country
        {
            get { return fCountry; }
            set { SetPropertyValue<string>(nameof(Country), ref fCountry, value); }
        }
        int fState;
        [Indexed(Name = @"iState_Customer")]
        public int State
        {
            get { return fState; }
            set { SetPropertyValue<int>(nameof(State), ref fState, value); }
        }
        string fZipCode;
        public string ZipCode
        {
            get { return fZipCode; }
            set { SetPropertyValue<string>(nameof(ZipCode), ref fZipCode, value); }
        }
        string fCity;
        public string City
        {
            get { return fCity; }
            set { SetPropertyValue<string>(nameof(City), ref fCity, value); }
        }
        string fAddress;
        public string Address
        {
            get { return fAddress; }
            set { SetPropertyValue<string>(nameof(Address), ref fAddress, value); }
        }
        string fTaxNumber;
        public string TaxNumber
        {
            get { return fTaxNumber; }
            set { SetPropertyValue<string>(nameof(TaxNumber), ref fTaxNumber, value); }
        }
        string fContactPerson;
        public string ContactPerson
        {
            get { return fContactPerson; }
            set { SetPropertyValue<string>(nameof(ContactPerson), ref fContactPerson, value); }
        }
        string fShipMode;
        public string ShipMode
        {
            get { return fShipMode; }
            set { SetPropertyValue<string>(nameof(ShipMode), ref fShipMode, value); }
        }
        string fPhone;
        public string Phone
        {
            get { return fPhone; }
            set { SetPropertyValue<string>(nameof(Phone), ref fPhone, value); }
        }
        string fEmailAddress;
        public string EmailAddress
        {
            get { return fEmailAddress; }
            set { SetPropertyValue<string>(nameof(EmailAddress), ref fEmailAddress, value); }
        }
        string fWeb;
        public string Web
        {
            get { return fWeb; }
            set { SetPropertyValue<string>(nameof(Web), ref fWeb, value); }
        }
        byte fStatus;
        public byte Status
        {
            get { return fStatus; }
            set { SetPropertyValue<byte>(nameof(Status), ref fStatus, value); }
        }
        bool fSupplier;
        public bool Supplier
        {
            get { return fSupplier; }
            set { SetPropertyValue<bool>(nameof(Supplier), ref fSupplier, value); }
        }
        [Association(@"BusinessSettingsReferencesCustomer")]
        public XPCollection<BusinessSettings> BusinessSettingsCollection { get { return GetCollection<BusinessSettings>(nameof(BusinessSettingsCollection)); } }
        [Association(@"CommonTrHeaderReferencesCustomer")]
        public XPCollection<CommonTrHeader> CommonTrHeaders { get { return GetCollection<CommonTrHeader>(nameof(CommonTrHeaders)); } }
        [Association(@"CommonTrTypeReferencesCustomer")]
        public XPCollection<CommonTrType> CommonTrTypes { get { return GetCollection<CommonTrType>(nameof(CommonTrTypes)); } }
    }

}
