//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class InsertType : XPObject
    {
        Producer fProducer;
        [Association(@"InsertTypeReferencesProducer")]
        public Producer Producer
        {
            get { return fProducer; }
            set { SetPropertyValue<Producer>(nameof(Producer), ref fProducer, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fType;
        public string Type
        {
            get { return fType; }
            set { SetPropertyValue<string>(nameof(Type), ref fType, value); }
        }
        double fColumns;
        public double Columns
        {
            get { return fColumns; }
            set { SetPropertyValue<double>(nameof(Columns), ref fColumns, value); }
        }
        double fRows;
        public double Rows
        {
            get { return fRows; }
            set { SetPropertyValue<double>(nameof(Rows), ref fRows, value); }
        }
        decimal fSectionWidth;
        public decimal SectionWidth
        {
            get { return fSectionWidth; }
            set { SetPropertyValue<decimal>(nameof(SectionWidth), ref fSectionWidth, value); }
        }
        decimal fSectionLength;
        public decimal SectionLength
        {
            get { return fSectionLength; }
            set { SetPropertyValue<decimal>(nameof(SectionLength), ref fSectionLength, value); }
        }
        byte[] fPhoto;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Photo
        {
            get { return fPhoto; }
            set { SetPropertyValue<byte[]>(nameof(Photo), ref fPhoto, value); }
        }
        byte fStatusCode;
        public byte StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<byte>(nameof(StatusCode), ref fStatusCode, value); }
        }
        [Association(@"LoadCarrierTypeReferencesInsertType")]
        public XPCollection<LoadCarrierType> LoadCarrierTypes { get { return GetCollection<LoadCarrierType>(nameof(LoadCarrierTypes)); } }
    }

}
