//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class LoadCarrier : XPObject
    {
        decimal fBarCode;
        public decimal BarCode
        {
            get { return fBarCode; }
            set { SetPropertyValue<decimal>(nameof(BarCode), ref fBarCode, value); }
        }
        LoadCarrierType fLcType;
        [Association(@"LoadCarrierReferencesLoadCarrierType")]
        public LoadCarrierType LcType
        {
            get { return fLcType; }
            set { SetPropertyValue<LoadCarrierType>(nameof(LcType), ref fLcType, value); }
        }
        string fRFID1;
        [Indexed(Name = @"Rfid1")]
        public string RFID1
        {
            get { return fRFID1; }
            set { SetPropertyValue<string>(nameof(RFID1), ref fRFID1, value); }
        }
        string fRFID2;
        public string RFID2
        {
            get { return fRFID2; }
            set { SetPropertyValue<string>(nameof(RFID2), ref fRFID2, value); }
        }
        byte fStatusCode;
        public byte StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<byte>(nameof(StatusCode), ref fStatusCode, value); }
        }
        bool fisEmpty;
        public bool isEmpty
        {
            get { return fisEmpty; }
            set { SetPropertyValue<bool>(nameof(isEmpty), ref fisEmpty, value); }
        }
        [Association(@"IocpReferencesLoadCarrier")]
        public XPCollection<Iocp> Iocps { get { return GetCollection<Iocp>(nameof(Iocps)); } }
        [Association(@"StockReferencesLoadCarrier")]
        public XPCollection<Stock> Stocks { get { return GetCollection<Stock>(nameof(Stocks)); } }
        [Association(@"StockHistoryReferencesLoadCarrier")]
        public XPCollection<StockHistory> StockHistories { get { return GetCollection<StockHistory>(nameof(StockHistories)); } }
        [Association(@"StorageLocationReferencesLoadCarrier")]
        public XPCollection<StorageLocation> StorageLocations { get { return GetCollection<StorageLocation>(nameof(StorageLocations)); } }
    }

}
