//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class LoadCarrierType : XPObject
    {
        Producer fProducer;
        [Association(@"LoadCarrierTypeReferencesProducer")]
        public Producer Producer
        {
            get { return fProducer; }
            set { SetPropertyValue<Producer>(nameof(Producer), ref fProducer, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        string fTypes;
        public string Types
        {
            get { return fTypes; }
            set { SetPropertyValue<string>(nameof(Types), ref fTypes, value); }
        }
        int fWidth;
        public int Width
        {
            get { return fWidth; }
            set { SetPropertyValue<int>(nameof(Width), ref fWidth, value); }
        }
        int fLength;
        public int Length
        {
            get { return fLength; }
            set { SetPropertyValue<int>(nameof(Length), ref fLength, value); }
        }
        int fHeight;
        public int Height
        {
            get { return fHeight; }
            set { SetPropertyValue<int>(nameof(Height), ref fHeight, value); }
        }
        int fWeight;
        public int Weight
        {
            get { return fWeight; }
            set { SetPropertyValue<int>(nameof(Weight), ref fWeight, value); }
        }
        double fMaxLoad;
        public double MaxLoad
        {
            get { return fMaxLoad; }
            set { SetPropertyValue<double>(nameof(MaxLoad), ref fMaxLoad, value); }
        }
        string fColor;
        public string Color
        {
            get { return fColor; }
            set { SetPropertyValue<string>(nameof(Color), ref fColor, value); }
        }
        InsertType fInsertType;
        [Association(@"LoadCarrierTypeReferencesInsertType")]
        public InsertType InsertType
        {
            get { return fInsertType; }
            set { SetPropertyValue<InsertType>(nameof(InsertType), ref fInsertType, value); }
        }
        System.Drawing.Image fPhoto;
        [Size(SizeAttribute.Unlimited)]
        [ValueConverter(typeof(DevExpress.Xpo.Metadata.ImageValueConverter))]
        [MemberDesignTimeVisibility(true)]
        public System.Drawing.Image Photo
        {
            get { return fPhoto; }
            set { SetPropertyValue<System.Drawing.Image>(nameof(Photo), ref fPhoto, value); }
        }
        byte fStatusCode;
        public byte StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<byte>(nameof(StatusCode), ref fStatusCode, value); }
        }
        [Association(@"LctProConReferencesLoadCarrierType")]
        public XPCollection<LctProCon> LctProCons { get { return GetCollection<LctProCon>(nameof(LctProCons)); } }
        [Association(@"LoadCarrierReferencesLoadCarrierType")]
        public XPCollection<LoadCarrier> LoadCarriers { get { return GetCollection<LoadCarrier>(nameof(LoadCarriers)); } }
        [Association(@"ProductReferencesLoadCarrierType")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
        [Association(@"QtyExchangeReferencesLoadCarrierType")]
        public XPCollection<QtyExchange> QtyExchanges { get { return GetCollection<QtyExchange>(nameof(QtyExchanges)); } }
    }

}
