//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class Producer : XPObject
    {
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        byte[] fLogo;
        [Size(SizeAttribute.Unlimited)]
        [MemberDesignTimeVisibility(true)]
        public byte[] Logo
        {
            get { return fLogo; }
            set { SetPropertyValue<byte[]>(nameof(Logo), ref fLogo, value); }
        }
        [Association(@"InsertTypeReferencesProducer")]
        public XPCollection<InsertType> InsertTypes { get { return GetCollection<InsertType>(nameof(InsertTypes)); } }
        [Association(@"LoadCarrierTypeReferencesProducer")]
        public XPCollection<LoadCarrierType> LoadCarrierTypes { get { return GetCollection<LoadCarrierType>(nameof(LoadCarrierTypes)); } }
        [Association(@"ProductReferencesProducer")]
        public XPCollection<Product> Products { get { return GetCollection<Product>(nameof(Products)); } }
    }

}
