//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class QtyExchange : XPObject
    {
        Product fProduct;
        [Association(@"QtyExchangeReferencesProduct")]
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        LoadCarrierType fLcType;
        [Association(@"QtyExchangeReferencesLoadCarrierType")]
        public LoadCarrierType LcType
        {
            get { return fLcType; }
            set { SetPropertyValue<LoadCarrierType>(nameof(LcType), ref fLcType, value); }
        }
        double fSourceQty;
        public double SourceQty
        {
            get { return fSourceQty; }
            set { SetPropertyValue<double>(nameof(SourceQty), ref fSourceQty, value); }
        }
        UnitType fTargetUnit;
        [Association(@"QtyExchangeReferencesUnitType")]
        public UnitType TargetUnit
        {
            get { return fTargetUnit; }
            set { SetPropertyValue<UnitType>(nameof(TargetUnit), ref fTargetUnit, value); }
        }
        double fTargetQty;
        public double TargetQty
        {
            get { return fTargetQty; }
            set { SetPropertyValue<double>(nameof(TargetQty), ref fTargetQty, value); }
        }
        bool fIn;
        public bool In
        {
            get { return fIn; }
            set { SetPropertyValue<bool>(nameof(In), ref fIn, value); }
        }
        bool fOut;
        public bool Out
        {
            get { return fOut; }
            set { SetPropertyValue<bool>(nameof(Out), ref fOut, value); }
        }
        decimal fPackageWidth;
        public decimal PackageWidth
        {
            get { return fPackageWidth; }
            set { SetPropertyValue<decimal>(nameof(PackageWidth), ref fPackageWidth, value); }
        }
        decimal fPackageLength;
        public decimal PackageLength
        {
            get { return fPackageLength; }
            set { SetPropertyValue<decimal>(nameof(PackageLength), ref fPackageLength, value); }
        }
        decimal fPackageHeight;
        public decimal PackageHeight
        {
            get { return fPackageHeight; }
            set { SetPropertyValue<decimal>(nameof(PackageHeight), ref fPackageHeight, value); }
        }
        double fPackageWeight;
        public double PackageWeight
        {
            get { return fPackageWeight; }
            set { SetPropertyValue<double>(nameof(PackageWeight), ref fPackageWeight, value); }
        }
        bool fDefault;
        [ColumnDbDefaultValue("((0))")]
        public bool Default
        {
            get { return fDefault; }
            set { SetPropertyValue<bool>(nameof(Default), ref fDefault, value); }
        }
        [Association(@"IocpReferencesQtyExchange")]
        public XPCollection<Iocp> Iocps { get { return GetCollection<Iocp>(nameof(Iocps)); } }
    }

}
