//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class Sorszam : XPObject
    {
        CommonTrType fType;
        [Association(@"SorszamReferencesCommonTrType")]
        public CommonTrType Type
        {
            get { return fType; }
            set { SetPropertyValue<CommonTrType>(nameof(Type), ref fType, value); }
        }
        int fLastNum;
        public int LastNum
        {
            get { return fLastNum; }
            set { SetPropertyValue<int>(nameof(LastNum), ref fLastNum, value); }
        }
        ushort fYear;
        public ushort Year
        {
            get { return fYear; }
            set { SetPropertyValue<ushort>(nameof(Year), ref fYear, value); }
        }
    }

}
