//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class Stock : XPObject
    {
        Product fProduct;
        [Association(@"StockReferencesProduct")]
        public Product Product
        {
            get { return fProduct; }
            set { SetPropertyValue<Product>(nameof(Product), ref fProduct, value); }
        }
        LoadCarrier fLC;
        [Association(@"StockReferencesLoadCarrier")]
        public LoadCarrier LC
        {
            get { return fLC; }
            set { SetPropertyValue<LoadCarrier>(nameof(LC), ref fLC, value); }
        }
        string fSection;
        public string Section
        {
            get { return fSection; }
            set { SetPropertyValue<string>(nameof(Section), ref fSection, value); }
        }
        double fNormalQty;
        public double NormalQty
        {
            get { return fNormalQty; }
            set { SetPropertyValue<double>(nameof(NormalQty), ref fNormalQty, value); }
        }
        double fReservedQty;
        public double ReservedQty
        {
            get { return fReservedQty; }
            set { SetPropertyValue<double>(nameof(ReservedQty), ref fReservedQty, value); }
        }
        double fBlockedQty;
        public double BlockedQty
        {
            get { return fBlockedQty; }
            set { SetPropertyValue<double>(nameof(BlockedQty), ref fBlockedQty, value); }
        }
        double fDispousedQty;
        public double DispousedQty
        {
            get { return fDispousedQty; }
            set { SetPropertyValue<double>(nameof(DispousedQty), ref fDispousedQty, value); }
        }
        byte fStatusCode;
        public byte StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<byte>(nameof(StatusCode), ref fStatusCode, value); }
        }
        StorageLocation fStorageLocation;
        [Association(@"StockReferencesStorageLocation")]
        public StorageLocation StorageLocation
        {
            get { return fStorageLocation; }
            set { SetPropertyValue<StorageLocation>(nameof(StorageLocation), ref fStorageLocation, value); }
        }
    }

}
