//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    public partial class StorageLocation : XPObject
    {
        Aisle fAisle;
        [Indexed(Name = @"iAisle_StorageLocation")]
        [Association(@"StorageLocationReferencesAisle")]
        public Aisle Aisle
        {
            get { return fAisle; }
            set { SetPropertyValue<Aisle>(nameof(Aisle), ref fAisle, value); }
        }
        byte fBlock;
        public byte Block
        {
            get { return fBlock; }
            set { SetPropertyValue<byte>(nameof(Block), ref fBlock, value); }
        }
        int fColumn;
        public int Column
        {
            get { return fColumn; }
            set { SetPropertyValue<int>(nameof(Column), ref fColumn, value); }
        }
        byte fRow;
        public byte Row
        {
            get { return fRow; }
            set { SetPropertyValue<byte>(nameof(Row), ref fRow, value); }
        }
        string fName;
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>(nameof(Name), ref fName, value); }
        }
        AbcType fAbcClass;
        [Indexed(Name = @"iAbcClass_StorageLocation")]
        public AbcType AbcClass
        {
            get { return fAbcClass; }
            set { SetPropertyValue<AbcType>(nameof(AbcClass), ref fAbcClass, value); }
        }
        int fLHU1X;
        public int LHU1X
        {
            get { return fLHU1X; }
            set { SetPropertyValue<int>(nameof(LHU1X), ref fLHU1X, value); }
        }
        int fLHU1Y;
        public int LHU1Y
        {
            get { return fLHU1Y; }
            set { SetPropertyValue<int>(nameof(LHU1Y), ref fLHU1Y, value); }
        }
        int fLHU2X;
        public int LHU2X
        {
            get { return fLHU2X; }
            set { SetPropertyValue<int>(nameof(LHU2X), ref fLHU2X, value); }
        }
        int fLHU2Y;
        public int LHU2Y
        {
            get { return fLHU2Y; }
            set { SetPropertyValue<int>(nameof(LHU2Y), ref fLHU2Y, value); }
        }
        int fHeight;
        public int Height
        {
            get { return fHeight; }
            set { SetPropertyValue<int>(nameof(Height), ref fHeight, value); }
        }
        LoadCarrier fLoadCarrier;
        [Indexed(Name = @"iLoadCarrier_StorageLocation")]
        [Association(@"StorageLocationReferencesLoadCarrier")]
        public LoadCarrier LoadCarrier
        {
            get { return fLoadCarrier; }
            set { SetPropertyValue<LoadCarrier>(nameof(LoadCarrier), ref fLoadCarrier, value); }
        }
        bool fLcIsEmpty;
        public bool LcIsEmpty
        {
            get { return fLcIsEmpty; }
            set { SetPropertyValue<bool>(nameof(LcIsEmpty), ref fLcIsEmpty, value); }
        }
        string fParentSlot;
        public string ParentSlot
        {
            get { return fParentSlot; }
            set { SetPropertyValue<string>(nameof(ParentSlot), ref fParentSlot, value); }
        }
        int fStatusCode;
        public int StatusCode
        {
            get { return fStatusCode; }
            set { SetPropertyValue<int>(nameof(StatusCode), ref fStatusCode, value); }
        }
        [Association(@"StockReferencesStorageLocation")]
        public XPCollection<Stock> Stocks { get { return GetCollection<Stock>(nameof(Stocks)); } }
    }

}
