//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace LogXExplorer.Module.BusinessObjects.Database
{

    [DeferredDeletion(false)]
    public partial class TransportOrder : XPObject
    {
        decimal fTpId;
        [Indexed(Name = @"idxTipId", Unique = true)]
        public decimal TpId
        {
            get { return fTpId; }
            set { SetPropertyValue<decimal>(nameof(TpId), ref fTpId, value); }
        }
        Iocp fIocp;
        [Association(@"TransportOrderReferencesIocp")]
        public Iocp Iocp
        {
            get { return fIocp; }
            set { SetPropertyValue<Iocp>(nameof(Iocp), ref fIocp, value); }
        }
        CommonTrHeader fCommonTrHeader;
        public CommonTrHeader CommonTrHeader
        {
            get { return fCommonTrHeader; }
            set { SetPropertyValue<CommonTrHeader>(nameof(CommonTrHeader), ref fCommonTrHeader, value); }
        }
        CommonTrDetail fCommonDetail;
        public CommonTrDetail CommonDetail
        {
            get { return fCommonDetail; }
            set { SetPropertyValue<CommonTrDetail>(nameof(CommonDetail), ref fCommonDetail, value); }
        }
        LoadCarrier fLC;
        public LoadCarrier LC
        {
            get { return fLC; }
            set { SetPropertyValue<LoadCarrier>(nameof(LC), ref fLC, value); }
        }
        int fType;
        public int Type
        {
            get { return fType; }
            set { SetPropertyValue<int>(nameof(Type), ref fType, value); }
        }
        StorageLocation fSourceLocation;
        public StorageLocation SourceLocation
        {
            get { return fSourceLocation; }
            set { SetPropertyValue<StorageLocation>(nameof(SourceLocation), ref fSourceLocation, value); }
        }
        StorageLocation fTargetLocation;
        public StorageLocation TargetLocation
        {
            get { return fTargetLocation; }
            set { SetPropertyValue<StorageLocation>(nameof(TargetLocation), ref fTargetLocation, value); }
        }
        byte fTargetTag;
        [ColumnDbDefaultValue("((0))")]
        public byte TargetTag
        {
            get { return fTargetTag; }
            set { SetPropertyValue<byte>(nameof(TargetTag), ref fTargetTag, value); }
        }
        DateTime fRecordingDate;
        public DateTime RecordingDate
        {
            get { return fRecordingDate; }
            set { SetPropertyValue<DateTime>(nameof(RecordingDate), ref fRecordingDate, value); }
        }
        string fmsgLocation;
        public string msgLocation
        {
            get { return fmsgLocation; }
            set { SetPropertyValue<string>(nameof(msgLocation), ref fmsgLocation, value); }
        }
        int fmsgStatus;
        public int msgStatus
        {
            get { return fmsgStatus; }
            set { SetPropertyValue<int>(nameof(msgStatus), ref fmsgStatus, value); }
        }
        bool fIsSendOpc;
        [ColumnDefaultValue(false)]
        public bool IsSendOpc
        {
            get { return fIsSendOpc; }
            set { SetPropertyValue<bool>(nameof(IsSendOpc), ref fIsSendOpc, value); }
        }
        int fWeight;
        public int Weight
        {
            get { return fWeight; }
            set { SetPropertyValue<int>(nameof(Weight), ref fWeight, value); }
        }
    }

}
